package com.akasi.eforex;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class usagersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "USAGERSDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "USAGERSDATA_ID_SEQ", name = "USAGERSDATA_ID_GENERATOR")
	@org.kie.api.definition.type.Label("Identifiant")
	private int id;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label("Id user")
	private com.akasi.eforex.usersData idUser;

	@org.kie.api.definition.type.Label("Reference permis coupe")
	private java.lang.String referencePermisCoupe;

	@org.kie.api.definition.type.Label("Created at")
	private String createdAt;

	@org.kie.api.definition.type.Label("Reference carte professionnelle")
	private java.lang.String referenceCarteProfessionnelle;

	public usagersData() {
	}

	public com.akasi.eforex.usersData getIdUser() {
		return this.idUser;
	}

	public void setIdUser(com.akasi.eforex.usersData idUser) {
		this.idUser = idUser;
	}

	public java.lang.String getReferencePermisCoupe() {
		return this.referencePermisCoupe;
	}

	public void setReferencePermisCoupe(java.lang.String referencePermisCoupe) {
		this.referencePermisCoupe = referencePermisCoupe;
	}

	public java.lang.String getReferenceCarteProfessionnelle() {
		return this.referenceCarteProfessionnelle;
	}

	public void setReferenceCarteProfessionnelle(
			java.lang.String referenceCarteProfessionnelle) {
		this.referenceCarteProfessionnelle = referenceCarteProfessionnelle;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public java.lang.String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.lang.String createdAt) {
		this.createdAt = createdAt;
	}

	public usagersData(int id, com.akasi.eforex.usersData idUser,
			java.lang.String referencePermisCoupe, java.lang.String createdAt,
			java.lang.String referenceCarteProfessionnelle) {
		this.id = id;
		this.idUser = idUser;
		this.referencePermisCoupe = referencePermisCoupe;
		this.createdAt = createdAt;
		this.referenceCarteProfessionnelle = referenceCarteProfessionnelle;
	}

}